[project]
name = "wagtail-unveil"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nick Moreton", email = "nickmoreton@me.com" }
]
requires-python = ">=3.9"
dependencies = [
    "wagtail>=6.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit",
    "ruff",
    "wagtail-modeladmin",
    "tox",
]
