[project]
name = "wagtail-unveil-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=4.2,<6.0",
    "wagtail>=7.0,<7.1",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "W"]

[tool.ruff.lint.per-file-ignores]
"sandbox/settings/*.py" = ["F403"]
"**/migrations/*.py" = ["E501"]

[tool.ruff.format]
quote-style = "double"

[dependency-groups]
dev = [
    "wagtail-modeladmin>=2.2.0",
]
