[tox]
env_list =
    py{310,311,312}-django42-wagtail70
    py{310,311,312,313}-django51-wagtail70
    py{310,311,312,313}-django52-wagtail70

[testenv]
deps =
    django42: django>=4.2,<4.3
    django51: django>=5.1,<5.2
    django52: django>=5.2,<5.3
    wagtail70: wagtail>=7.0,<7.1
    wagtail-modeladmin>=2.2.0
set_env =
    DJANGO_SETTINGS_MODULE = sandbox.settings
    PYTHONPATH = {toxinidir}
commands =
    django-admin test tests {posargs}
