# Generated by Django 5.2.4 on 2025-07-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_book_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
