# Generated by Django 5.2.4 on 2025-07-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleSnippetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Example Snippet',
                'verbose_name_plural': 'Example Snippets',
            },
        ),
        migrations.CreateModel(
            name='ExampleSnippetViewSetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Example Snippet ViewSet',
                'verbose_name_plural': 'Example Snippet ViewSets',
            },
        ),
    ]
