# Generated by Django 5.2.4 on 2025-07-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("for_snippets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleSnippetViewSetModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Example Snippet ViewSet",
                "verbose_name_plural": "Example Snippet ViewSets",
            },
        ),
    ]
