# Generated by Django 5.2.4 on 2025-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("for_snippets", "0002_examplesnippetviewsetmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examplesnippetmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="examplesnippetviewsetmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
