# Generated by Django 5.2.11 on 2026-02-26 21:11

import wagtail.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("body", wagtail.fields.RichTextField(blank=True)),
                ("call_to_action_url", models.URLField(blank=True)),
                ("call_to_action_text", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "banner",
                "verbose_name_plural": "banners",
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Colour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "colour",
                "verbose_name_plural": "colours",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("job_title", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
            },
        ),
    ]
