# Generated by Django 5.2.4 on 2025-07-09 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplepagemodelbasic',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Optional banner image for the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='examplepagemodelstandard',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Optional banner image for the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
