# Generated by Django 5.2.4 on 2025-07-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_examplewagtailmodeladminmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleWagtailModeladminModel',
        ),
    ]
