# Generated by Django 5.2.4 on 2025-07-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_examplewagtailmodeladminmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleWagtailModeladminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
