# Generated by Django 5.2.4 on 2025-07-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_examplewagtailmodeladminmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplewagtailmodeladminmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
