# Generated by Django 5.2.4 on 2025-07-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_examplefootergenericsettings_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExampleFooterSiteSettings',
            new_name='ExampleMessageSiteSettings',
        ),
    ]
