# Generated by Django 5.2.4 on 2025-07-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_examplefootersitesettings_examplemessagesitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplefootergenericsettings',
            name='footer',
            field=models.TextField(blank=True, help_text='This is the footer text that will be displayed on all pages.'),
        ),
    ]
